### ISSUE TITLE
Link to deployed app

### ISSUE THREAD

**Issue by axeberg** [zavham/weatherapp#1]

**Comment by zavham** [comment]
http://zavham.chas.academy/weatherapp/ 
(open in Microsoft edge)

**Comment by axeberg** [comment]
@zavham I most definitely will not open it in IE. And you can't deploy an app that only works in IE...

**Comment by axeberg** [comment]
At the very least provide a fallback solution where the user gets to input a location using text.

**Comment by zavham** [comment]
@axelolsson the issue is fixed. User can search for weather by typing in his/her location as country/citry and etc.

**Comment by axeberg** [comment]
@zavham Missing some font-icons here, as you're using my crappy design, but that's fine I guess - I would fix that if you're going to show this on your portfolio.

**Comment by axeberg** [comment]
Furthermore, I find it kind of confusing (as a user) to have two buttons. Especially since the first button is supposed to get the weather based on location.

As a user I would expect this:

1. I visit the site, and if geolocation is available on my client - try and fetch the weather using the geolocation API. Should that fail, fade step 2 in but still show a "Try and fetch weather on my location".

2. I visit the site and geolocation is *not* available on my client - I see one button, and the input field to input the name of the city I want to get weather for.
